#!/usr/bin/env python3
"""
Convert manuscript .tex files to .docx via pandoc, matching the style of
manuscript.docx / manuscript_supplementary.docx (originally generated by
Microsoft Word on Mac).

Usage:
    python convert_tex_to_docx.py                    # convert m.tex → m.docx, m_s.tex → m_s.docx
    python convert_tex_to_docx.py --input foo.tex    # single file mode
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# Input → (output .docx, reference .docx for style)
CONVERSIONS = [
    ("m.tex", "m.docx", "manuscript.docx"),
    ("m_s.tex", "m_s.docx", "manuscript_supplementary.docx"),
]


def find_pandoc() -> str:
    """Locate pandoc binary: PATH first, then pypandoc fallback."""
    import shutil

    path = shutil.which("pandoc")
    if path:
        return path
    try:
        import pypandoc

        return pypandoc.get_pandoc_path()
    except Exception:
        print("pandoc not found. Install pandoc or `pip install pypandoc`.")
        sys.exit(1)


def convert_one(
    tex_path: Path,
    docx_path: Path,
    ref_docx: Path | None = None,
    *,
    verbose: bool = True,
) -> bool:
    """Convert a single .tex to .docx via pandoc."""
    args = [
        "pandoc",
        str(tex_path),
        "-f",
        "latex",
        "-t",
        "docx",
        "-o",
        str(docx_path),
        "--standalone",
        "--bibliography=/dev/null",  # suppress missing .bib warnings
        "--metadata=link-citations=false",
        "--pdf-engine=xelatex",
    ]
    if ref_docx and ref_docx.exists():
        args += ["--reference-doc", str(ref_docx)]

    if verbose:
        print(f"  {tex_path.name} → {docx_path.name}", end="")
        if ref_docx and ref_docx.exists():
            print(f"  (style: {ref_docx.name})", end="")
        print()

    try:
        result = subprocess.run(
            args,
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode != 0:
            # pandoc often succeeds with warnings on stderr;
            # only treat as failure if output file is missing
            if not docx_path.exists():
                print(f"  ERROR: {result.stderr[-800:]}", file=sys.stderr)
                return False
            print(f"  WARNING (non-zero exit but .docx written): {result.stderr[-300:]}")
        if verbose:
            size_kb = docx_path.stat().st_size / 1024
            print(f"  → {size_kb:.0f} KB")
        return True
    except subprocess.TimeoutExpired:
        print(f"  TIMEOUT converting {tex_path.name}", file=sys.stderr)
        return False
    except Exception as exc:
        print(f"  ERROR: {exc}", file=sys.stderr)
        return False


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert .tex → .docx via pandoc")
    parser.add_argument("--input", "-i", help="Single .tex file to convert")
    parser.add_argument("--output", "-o", help="Output .docx path (single-file mode)")
    parser.add_argument(
        "--reference", "-r", help="Reference .docx for styling (single-file mode)"
    )
    parser.add_argument("--verbose", "-v", action="store_true", default=True)
    args = parser.parse_args()

    pandoc_bin = find_pandoc()
    print(f"pandoc: {pandoc_bin}")

    if args.input:
        tex = Path(args.input)
        if not tex.is_absolute():
            tex = ROOT / tex
        docx = Path(args.output) if args.output else tex.with_suffix(".docx")
        if not docx.is_absolute():
            docx = ROOT / docx
        ref = Path(args.reference) if args.reference else None
        if ref and not ref.is_absolute():
            ref = ROOT / ref
        ok = convert_one(tex, docx, ref, verbose=args.verbose)
        return 0 if ok else 1

    # Batch mode: m.tex + m_s.tex
    ok = True
    for tex_name, docx_name, ref_name in CONVERSIONS:
        tex = ROOT / tex_name
        docx = ROOT / docx_name
        ref = ROOT / ref_name
        if not tex.exists():
            print(f"SKIP: {tex} not found")
            continue
        if not convert_one(tex, docx, ref, verbose=args.verbose):
            ok = False
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
